--- #YAML:1.0
name:                LWP-UserAgent-WithCache
version:             0.12
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::FileCache:              0
    File::HomeDir:                 0
    LWP::UserAgent:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
